include: package:lint/analysis_options.yaml
linter:
  rules:
    package_api_docs: true
    parameter_assignments: true
    prefer_function_declarations_over_variables: false
    ambiguous_extension_member_access: false
analyzer:
  exclude:
    - pubspec.yaml

  errors:
    missing_required_param: error
    parameter_assignments: error
