name: flicked_cards
description: A gesture driven customizable and extensible card widget
version: 0.0.3
homepage: https://danielcardona.dev
repository: https://github.com/DanielCardonaRojas/flicked_cards

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail:

flutter:
