name: flicked_cards
description: A gesture driven customizable and extensible card widget
version: 0.0.1
homepage: danielcardona.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail:
  flutter_test:
    sdk: flutter

flutter:
